# Generated by Django 6.0.2 on 2026-03-02 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=255)),
                ("is_pleasant", models.BooleanField(default=False)),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Ежедневно"),
                            (2, "Раз в 2 дня"),
                            (3, "Раз в 3 дня"),
                            (4, "Раз в 4 дня"),
                            (5, "Раз в 5 дней"),
                            (6, "Раз в 6 дней"),
                            (7, "Раз в неделю"),
                        ],
                        default=1,
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=255)),
                ("duration", models.PositiveIntegerField(default=120)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
